# Generated by Django 5.1.5 on 2025-02-03 20:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0002_alter_allergen_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('starter', 'Starters'), ('burger', 'Burgers'), ('side', 'Sides'), ('dessert', 'Desserts'), ('drink', 'Drinks')])),
                ('description', models.TextField()),
                ('item_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('allergens', models.ManyToManyField(blank=True, to='booking.allergen')),
            ],
        ),
    ]
